version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"

sphinx:
  configuration: docs/source/conf.py    

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .

formats:
  - pdf
  - epub      