---
router:
  hosts:
    R1:
      ansible_host: 9.9.9.101
    R2:
      ansible_host: 9.9.9.102
    R3:
      ansible_host: 9.9.9.103

switch:
  hosts:
    SW1:
      ansible_host: 9.9.9.100
      ansible_become: true
      ansible_become_method: enable
      ansible_become_password: cisco

linux:
  hosts:
    ubuntu:
      ansible_host: 9.9.9.99
      ansible_user: ubuntu
      ansible_password: server

cisco:
  children:
    router:
    switch:

  vars:
    ansible_network_os: ios
    ansible_password: cisco
    ansible_connection: network_cli