[tool.poetry]
name = "ansible book"
version = "1.0"
description = "Ansible Quick Start Guide"
authors = ["syed asif <sydasif78@gmail.com>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
